sudo: 'required'
services:
  - 'docker'

language: bash

jobs:
  include:
    - &buildandtest
      stage: test
      if: (type = pull_request)
      before_script: docker build --build-arg TARGET=${TARGET} -t vmq-travis -f ${DOCKERFILE} .
      script: docker run vmq-travis vernemq
      env: null
    
    - <<: *buildandtest
      env:
        - DOCKERFILE=Dockerfile TARGET=rel TAG_SUFFIX=""

    - <<: *buildandtest
      env:
        - DOCKERFILE=Dockerfile.alpine TARGET=rel TAG_SUFFIX="-alpine"

    - &buildlatest
      stage: deploy
      if: (type != pull_request) AND (branch = master)
      before_script: docker build --build-arg TARGET=${TARGET} -t vmq-travis -f ${DOCKERFILE} .
      script: docker tag vmq-travis vernemq/vernemq:latest$TAG_SUFFIX
      env: null
    
    - <<: *buildlatest
      env:
        - DOCKERFILE=Dockerfile TARGET=rel TAG_SUFFIX=""

    - <<: *buildlatest
      env:
        - DOCKERFILE=Dockerfile.alpine TARGET=rel TAG_SUFFIX="-alpine"

    - &buildtag 
      stage: deploy
      if: (type != pull_request) AND (tag IS present) AND (branch = master)
      before_script: docker build --build-arg TARGET=${TARGET} -t vmq-travis -f ${DOCKERFILE} .
      script: docker tag vmq-travis vernemq/vernemq:$TRAVIS_TAG$TAG_SUFFIX
      env: null
    
    - <<: *buildtag
      env:
        - DOCKERFILE=Dockerfile TARGET=rel TAG_SUFFIX=""

    - <<: *buildtag
      env:
        - DOCKERFILE=Dockerfile.alpine TARGET=rel TAG_SUFFIX="-alpine"
