sudo: 'required'
services:
  - 'docker'
stages:
  - name: test
  - name: push-latest
    if: (type != pull_request) AND (branch = master)
  - name: push-tag
    if: (type != pull_request) AND (tag IS present) AND (branch = master)

env:
  - DOCKERFILE=Dockerfile TARGET=rel TAG_SUFFIX=""
  - DOCKERFILE=Dockerfile.alpine TARGET=rel TAG_SUFFIX="-alpine"
#  - DOCKERFILE=Dockerfile TARGET=swc TAG_SUFFIX="-swc"
#  - DOCKERFILE=Dockerfile.alpine TARGET=swc TAG_SUFFIX="-swc-alpine"

matrix:
  fast_finish: true

before_install:
  - docker build --build-arg TARGET=${TARGET}
                 -t vmq-travis
                 -f ${DOCKERFILE} .

jobs:
  include:
    - stage: test
      script: docker run vmq-travis vernemq

    - stage: push-latest
      script: docker tag vmq-travis vernemq/vernemq:latest$TAG_SUFFIX

    - stage: push-tag
      script: docker tag vmq-travis vernemq/vernemq:$TRAVIS_TAG$TAG_SUFFIX
