sudo: 'required'
services:
  - 'docker'

language: bash

env:
  - DOCKERFILE=Dockerfile TARGET=rel TAG_SUFFIX=""
  - DOCKERFILE=Dockerfile.alpine TARGET=rel TAG_SUFFIX="-alpine"
#  - DOCKERFILE=Dockerfile TARGET=swc TAG_SUFFIX="-swc"
#  - DOCKERFILE=Dockerfile.alpine TARGET=swc TAG_SUFFIX="-swc-alpine"

jobs:
  include:
    - name: "Build docker image"
      script: docker build --build-arg TARGET=${TARGET} -t vmq-travis -f ${DOCKERFILE} .

    - name: "Test docker image"
      script: docker run vmq-travis vernemq

    - name: "Tag latest"
      if: (type != pull_request) AND (branch = master)
      script: docker tag vmq-travis vernemq/vernemq:latest$TAG_SUFFIX

    - name: "Tag version"
      if: (type != pull_request) AND (tag IS present) AND (branch = master)
      script: docker tag vmq-travis vernemq/vernemq:$TRAVIS_TAG$TAG_SUFFIX
