sudo: 'required'
services:
  - 'docker'

language: bash

stages:
  - name: test
  - name: push-latest
    if: (type != pull_request) AND (branch = master)
  - name: push-tag
    if: (type != pull_request) AND (tag IS present) AND (branch = master)

env:
  - DOCKERFILE=Dockerfile TARGET=rel TAG_SUFFIX=""
  - DOCKERFILE=Dockerfile.alpine TARGET=rel TAG_SUFFIX="-alpine"
#  - DOCKERFILE=Dockerfile TARGET=swc TAG_SUFFIX="-swc"
#  - DOCKERFILE=Dockerfile.alpine TARGET=swc TAG_SUFFIX="-swc-alpine"

jobs:
  include:
    - &buildimage
      before_script: docker build --build-arg TARGET=${TARGET} -t vmq-travis -f ${DOCKERFILE} .
      script: docker run vmq-travis vernemq
      after_success: null

    - <<: *buildimage
      stage: test

    - <<: *buildimage
      stage: push-latest
      after_success: docker tag vmq-travis vernemq/vernemq:latest$TAG_SUFFIX

    - <<: *buildimage
      stage: push-tag
      after_success: docker tag vmq-travis vernemq/vernemq:$TRAVIS_TAG$TAG_SUFFIX
